import Head from "next/head";
import Header from "../components/common/Header";
import { useRouter } from "next/router";

export default function RetailerPage() {
  const checkoutCreateCartUrl = "http://localhost:5000/api/cart";
  const router = useRouter();
  const request = {
    products: [
      {
        quantity: 1,
        productCode: "shoe",
        grossPrice: 100,
      },
    ],
  };
  const requestOptions = {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(request),
  };

  async function createCart() {
    const response = await fetch(checkoutCreateCartUrl, requestOptions);
    const result = await response.json();
    router.push(`${result.cartUrl}`);
  }
  return (
    <div>
      <Head>
        <title>Retailer webshop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex flex-row justify-center">
        <div className="flex flex-wrap mb-3 justify-center">
          <button
            className="rounded-full py-3 px-6 bg-[#171717] hover:bg-gray-700 w-full text-white"
            onClick={() => createCart()}
          >
            Start checkout flow
          </button>
        </div>
      </div>
    </div>
  );
}
